baseurl = "http://axross.github.io/blog/"
contentdir = "content"
publishdir = "public"

[indexes]
  category = "categories"

languageCode = "ja-jp"
title = "My New Hugo Site"
theme = "casper"
canonifyurls = true
