baseurl = "http://axross.github.io/blog/"
contentdir = "content"
publishdir = "public"
languageCode = "ja-jp"
title = "My New Hugo Site"
canonifyurls = true
theme = "casper"

[indexes]
  category = "categories"
